version: '3.9'

services:
  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --reload --port 80 --host 0.0.0.0
    ports:
      - "80:80"
    depends_on:
      - postgres_db
      - redis_db

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis_db:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"

  celery:
    build: 
      context: .
    depends_on:
      - redis_db
    command: celery -A auth.tasks:celery worker --loglevel=INFO --pool=solo

    