"""Changed user model

Revision ID: 06d2fb98902a
Revises: 4c8a4eea05ef
Create Date: 2024-08-02 18:37:32.414611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d2fb98902a'
down_revision: Union[str, None] = '4c8a4eea05ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
