"""changed review model

Revision ID: 2171fd51ded2
Revises: 422806539a37
Create Date: 2024-09-02 20:04:42.759212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2171fd51ded2'
down_revision: Union[str, None] = '422806539a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_login', sa.String(), nullable=False))
    op.add_column('review', sa.Column('mentor_login', sa.String(), nullable=False))
    op.drop_constraint('review_review_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_mentor_id_fkey', 'review', type_='foreignkey')
    op.drop_column('review', 'mentor_id')
    op.drop_column('review', 'review_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('review_mentor_id_fkey', 'review', 'user', ['mentor_id'], ['id'])
    op.create_foreign_key('review_review_id_fkey', 'review', 'user', ['review_id'], ['id'])
    op.drop_column('review', 'mentor_login')
    op.drop_column('review', 'review_login')
    # ### end Alembic commands ###
