"""added start_time line in meeting table

Revision ID: 363e91f5fdfd
Revises: 195a6974178c
Create Date: 2024-08-21 19:18:59.599276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363e91f5fdfd'
down_revision: Union[str, None] = '195a6974178c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('start_time', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'start_time')
    # ### end Alembic commands ###
